#!/bin/env python3

import re
from mistletoe.span_token import SpanToken

class Wangle(SpanToken):
    pattern = re.compile(r"\?{3}(.*?)\?{3}", re.DOTALL)
    def __init__(self, match):
        self.match = match.group(1)

class GithubWiki(SpanToken):
    pattern = re.compile(r"\[\[ *(.+?) *\| *(.+?) *\]\]")
    def __init__(self, match_obj):
        self.target = match_obj.group(2)

from mistletoe.html_renderer import HTMLRenderer

def escape_url(x):
    return f"<<{x}>>"

class GithubWikiRenderer(HTMLRenderer):
    def __init__(self):
        super().__init__(Wangle)

    def render_github_wiki(self, token):
        template = '<a href="{target}">{inner}</a>'
        target = escape_url(token.target)
        inner = self.render_inner(token)
        return template.format(target=target, inner=inner)

    def render_wangle(self, token):
        return "WANGLE!!"

from mistletoe import Document

with open('foo.md', 'r') as fin:
    with GithubWikiRenderer() as renderer:
        rendered = renderer.render(Document(fin))
        print(rendered)
